import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import localFont from "next/font/local";
import BookingButton from "@/components/BookingButton";
import WhatsAppButton from "@/components/WhatsAppButton";
import EmailButton from "@/components/EmailButton";
import { Quattrocento } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

// Configure the font
const quattrocento = Quattrocento({
    weight: ['400', '700'], // Choose the weights you need
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${quattrocento.className}`}>
                <Header />
                {children}
                <Footer />

                <div style={{ position: "fixed", right: "1rem", bottom: "1rem" }}>
                    <BookingButton />
                </div>

                <div style={{ position: "fixed", left: "1rem", bottom: "4.5rem" }}>
                    <EmailButton />
                </div>

                <div style={{ position: "fixed", left: "1rem", bottom: "1rem" }}>
                    <WhatsAppButton />
                </div>
            </body>
        </html>
    );
}
